# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: everyday df3ndr
email: info@df3ndr.io
description: Microsoft security tips and tricks on your favorite Podcast platform
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://df3ndr.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: df3ndr.io
github_username: everday-df3ndr
header_pages:
  - index.md
  - about.md
  - contact.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true
footer: 'follow us on <a href="https://bsky.app/profile/df3ndr.io">Bluesky</a> or <a href="https://cgoosen.me/going/8?https://infosec.exchange/@df3ndr">Mastodon</a>'
google_analytics: G-QH118866XT

# Build settings
#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
